version: '2'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  hw-worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    depends_on:
      - redis
    links:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/1
  hw-client:
    build:
      context: .
      dockerfile: Dockerfile-client
    depends_on:
      - redis
      - hw-worker
    links:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/1
